const RAW_COUNTRY_ALIASES = {
    PT: ['portugal'],
    ES: ['spain', 'espanha'],
    FR: ['france', 'franca'],
    DE: ['germany', 'alemanha'],
    IT: ['italy', 'italia'],
    GB: ['united kingdom', 'uk', 'reino unido', 'great britain', 'england', 'scotland', 'wales'],
    IE: ['ireland', 'irlanda'],
    NL: ['netherlands', 'holland', 'paises baixos'],
    BE: ['belgium', 'belgica'],
    LU: ['luxembourg', 'luxemburgo'],
    CH: ['switzerland', 'suica'],
    AT: ['austria'],
    DK: ['denmark', 'dinamarca'],
    NO: ['norway', 'noruega'],
    SE: ['sweden', 'suecia'],
    FI: ['finland', 'finlandia'],
    IS: ['iceland', 'islandia'],
    PL: ['poland', 'polonia'],
    CZ: ['czech republic', 'czechia', 'republica checa'],
    SK: ['slovakia', 'eslovaquia'],
    HU: ['hungary', 'hungria'],
    RO: ['romania', 'romenia'],
    BG: ['bulgaria', 'bulgaria'],
    GR: ['greece', 'grecia'],
    TR: ['turkey', 'turkiye', 'turquia'],
    HR: ['croatia', 'croacia'],
    RS: ['serbia', 'servia'],
    SI: ['slovenia', 'eslovenia'],
    BA: ['bosnia and herzegovina', 'bosnia', 'bosnia herzegovina', 'bosnia e herzegovina'],
    ME: ['montenegro'],
    AL: ['albania', 'albania'],
    MK: ['north macedonia', 'macedonia do norte', 'macedonia'],
    UA: ['ukraine', 'ucrania'],
    BY: ['belarus', 'bielorrussia'],
    LT: ['lithuania', 'lituania'],
    LV: ['latvia', 'letonia'],
    EE: ['estonia', 'estonia'],
    RU: ['russia', 'russia'],
    MD: ['moldova', 'moldavia'],
    CY: ['cyprus', 'chipre'],
    MT: ['malta'],

    US: ['united states', 'united states of america', 'usa', 'estados unidos'],
    CA: ['canada', 'canada'],
    MX: ['mexico', 'mexico'],
    CR: ['costa rica'],
    PA: ['panama', 'panama'],
    JM: ['jamaica', 'jamaica'],
    HT: ['haiti', 'haiti'],
    HN: ['honduras'],
    SV: ['el salvador'],
    GT: ['guatemala'],
    NI: ['nicaragua'],
    DO: ['dominican republic', 'dominican rep.', 'republica dominicana'],
    CU: ['cuba'],
    TT: ['trinidad and tobago', 'trinidad e tobago'],

    BR: ['brazil', 'brasil'],
    AR: ['argentina', 'argentina'],
    UY: ['uruguay', 'uruguai'],
    PY: ['paraguay', 'paraguai'],
    CL: ['chile', 'chile'],
    BO: ['bolivia', 'bolivia'],
    PE: ['peru', 'peru'],
    EC: ['ecuador', 'equador'],
    CO: ['colombia', 'colombia'],
    VE: ['venezuela', 'venezuela'],

    MA: ['morocco', 'marrocos'],
    DZ: ['algeria', 'argelia'],
    TN: ['tunisia', 'tunisia'],
    EG: ['egypt', 'egito'],
    LY: ['libya', 'libia'],
    SD: ['sudan', 'sudao'],
    SN: ['senegal', 'senegal'],
    CI: ['ivory coast', 'cote divoire', 'cote d ivoire', 'costa do marfim'],
    GH: ['ghana', 'gana'],
    NG: ['nigeria', 'nigeria'],
    CM: ['cameroon', 'camaroes'],
    ML: ['mali', 'mali'],
    BF: ['burkina faso'],
    GN: ['guinea', 'guine'],
    GA: ['gabon', 'gabao'],
    CD: ['dr congo', 'democratic republic of the congo', 'congo democratico', 'congo dr', 'rd congo'],
    CG: ['republic of the congo', 'congo', 'congo republic'],
    AO: ['angola', 'angola'],
    ZA: ['south africa', 'africa do sul'],
    MZ: ['mozambique', 'mocambique'],
    ZM: ['zambia', 'zambia'],
    KE: ['kenya', 'quenia'],
    ET: ['ethiopia', 'etiopia'],
    UG: ['uganda', 'uganda'],
    TZ: ['tanzania', 'tanzania'],
    RW: ['rwanda', 'ruanda'],
    BI: ['burundi', 'burundi'],
    MG: ['madagascar', 'madagascar'],

    JP: ['japan', 'japao'],
    KR: ['south korea', 'korea do sul', 'south korea republic', 'korea republic', 'republic of korea'],
    KP: ['north korea', 'korea do norte'],
    CN: ['china', 'china'],
    TW: ['taiwan', 'taiwan'],
    HK: ['hong kong'],
    MN: ['mongolia', 'mongolia'],
    VN: ['vietnam', 'vietname'],
    TH: ['thailand', 'tailandia'],
    MY: ['malaysia', 'malasia'],
    SG: ['singapore', 'singapura'],
    ID: ['indonesia', 'indonesia'],
    PH: ['philippines', 'filipinas'],
    IN: ['india', 'india'],
    PK: ['pakistan', 'paquistao'],
    BD: ['bangladesh', 'bangladesh'],
    LK: ['sri lanka'],
    NP: ['nepal', 'nepal'],
    IR: ['iran', 'irao'],
    IQ: ['iraq', 'iraque'],
    SA: ['saudi arabia', 'arabia saudita'],
    QA: ['qatar', 'catar'],
    AE: ['united arab emirates', 'uae', 'emirados arabes unidos'],
    OM: ['oman', 'oma'],
    JO: ['jordan', 'jordania'],
    IL: ['israel', 'israel'],
    LB: ['lebanon', 'libano'],
    SY: ['syria', 'siria'],
    KZ: ['kazakhstan', 'cazaquistao'],
    UZ: ['uzbekistan', 'usbequistao'],
    TM: ['turkmenistan', 'turquemenistao'],
    KG: ['kyrgyzstan', 'quirguistao'],
    TJ: ['tajikistan', 'tajiquistao'],

    AU: ['australia', 'australia'],
    NZ: ['new zealand', 'nova zelandia'],
    FJ: ['fiji', 'fiji'],
    PG: ['papua new guinea', 'papua nova guine'],
    NC: ['new caledonia', 'nova caledonia']
};

function normalizeCountryName(value = '') {
    return value
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '')
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, ' ')
        .trim();
}

const COUNTRY_NAME_TO_ISO = Object.entries(RAW_COUNTRY_ALIASES).reduce((acc, [iso, aliases]) => {
    aliases.forEach((alias) => {
        acc[normalizeCountryName(alias)] = iso;
    });
    return acc;
}, {});

export { COUNTRY_NAME_TO_ISO, normalizeCountryName };
